from enum import Enum

class Profession(Enum):
    """
    전문 계열Profession은 고유의 스킬을 가지는 캐릭터입니다
    """
    HERO = "hero"
    PALADIN = "paladin"
    DARK_KNIGHT = "dark_knight"
    ARCH_MAGE_FIRE_POISON = "arch_mage_fire_poison"
    ARCH_MAGE_ICE_LIGHTNING = "arch_mage_ice_lightning"
    BISHOP = "bishop"
    BOWMASTER = "bowmaster"
    MARKSMAN = "marksman"
    PATHFINDER = "pathfinder"
    NIGHT_LORD = "night_lord"
    SHADOWER = "shadower"
    DUAL_BLADE = "dual_blade"
    VIPER = "viper"
    CAPTAIN = "captain"
    CANNON_SHOOTER = "cannon_shooter"
    SOUL_MASTER = "soul_master"
    FLAME_WIZARD = "flame_wizard"
    WIND_BREAKER = "wind_breaker"
    NIGHT_WALKER = "night_walker"
    STRIKER = "striker"
    MICHAEL = "michael"
    BLASTER = "blaster"
    BATTLE_MAGE = "battle_mage"
    WILD_HUNTER = "wild_hunter"
    MECHANIC = "mechanic"
    DEMON_SLAYER = "demon_slayer"
    DEMON_AVENGER = "demon_avenger"
    XENON = "xenon"
    MERCEDES = "mercedes"
    ARAN = "aran"
    PHANTOM = "phantom"
    LUMINOUS = "luminous"
    EVAN = "evan"
    EUNWOL = "eunwol"
    KAISER = "kaiser"
    KAIN = "kain"
    CADENA = "cadena"
    ANGELIC_BUSTER = "angelic_buster"
    ADELE = "adele"
    ILLIUM = "illium"
    KHALI = "khali"
    ARK = "ark"
    LARA = "lara"
    HOYOUNG = "hoyoung"
    ZERO = "zero"
    KINESIS = "kinesis"
    